# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963dafee2a26b194a6eae2c3e3acc3313f426dbc15b2beb4c78a0a5327564f71a71aaa9953b2cfc7d6c0f32d61ae3dff508f6aab8fdcb0c48e4a3db0b5c3441c

test:
  secret_key_base: 5abcd315c4b6b5833989b5a2788c404e3dc7e854bb6e0618e3ffe8484bcf47eeebf47f282ba48156a21632a98e8d46f6ee4f9519fba759baa3035d29f4eafa08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
